[package]
name = "piskec"
description = "Piske programming language transpiler"
version = "0.1.0"
authors = ["Jamie Blondin <jblondin@gmail.com>"]
repository = "https://github.com/jblondin/piske"

[[bin]]
name = "piskec"

[dependencies]
cargo = "0.23.0"
piske = { path = "../" }
